#!/usr/bin/env python3
"""Convert an SVG into an LVGL v9 image C source (ARGB8888).

Usage:
    python3 svg_to_lvgl.py <input.svg> <size_px> <symbol_name> <output.c>

Requires `rsvg-convert` (brew install librsvg) for alpha-correct
rasterization, and Pillow for pixel access. The output targets LVGL v9's
`lv_image_dsc_t` header format (LV_COLOR_FORMAT_ARGB8888), matching the
`lvgl/lvgl: ^9` managed component pinned in firmware/main/idf_component.yml.

Byte order per pixel is B, G, R, A (little-endian ARGB8888, as stored by
LVGL on the ESP32-S3's little-endian Xtensa core).

Regenerate the Helios boot logo with:
    python3 tools/asset-gen/svg_to_lvgl.py \\
        assets/brand/helios-logo.svg 220 helios_logo \\
        firmware/ui/animations/assets/helios_logo.c
"""
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install pillow")


def rasterize(svg_path: Path, size: int) -> "Image.Image":
    with tempfile.NamedTemporaryFile(suffix=".png") as tmp:
        subprocess.run(
            [
                "rsvg-convert",
                "-w", str(size),
                "-h", str(size),
                "--background-color=none",
                str(svg_path),
                "-o", tmp.name,
            ],
            check=True,
        )
        return Image.open(tmp.name).convert("RGBA").copy()


def to_c_array(img: "Image.Image", symbol: str, source_svg: str) -> str:
    w, h = img.size
    pixels = img.load()
    out = []
    out.append(
        f"/* Generated by tools/asset-gen/svg_to_lvgl.py from {source_svg}.\n"
        f"   Do not edit by hand — regenerate instead. */\n"
    )
    out.append(f'#include "lvgl.h"\n')
    out.append(f"#ifndef LV_ATTRIBUTE_MEM_ALIGN\n#define LV_ATTRIBUTE_MEM_ALIGN\n#endif\n")
    out.append(
        f"const LV_ATTRIBUTE_MEM_ALIGN uint8_t {symbol}_map[] = {{\n"
    )
    row_chunks = []
    for y in range(h):
        row_bytes = []
        for x in range(w):
            r, g, b, a = pixels[x, y]
            # LVGL ARGB8888 little-endian byte order: B, G, R, A.
            row_bytes.extend((b, g, r, a))
        row_chunks.append(
            "  " + ", ".join(f"0x{v:02x}" for v in row_bytes) + ","
        )
    out.append("\n".join(row_chunks))
    out.append("\n};\n\n")
    out.append(
        f"const lv_image_dsc_t {symbol} = {{\n"
        f"    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
        f"    .header.cf = LV_COLOR_FORMAT_ARGB8888,\n"
        f"    .header.flags = 0,\n"
        f"    .header.w = {w},\n"
        f"    .header.h = {h},\n"
        f"    .header.stride = {w} * 4,\n"
        f"    .data_size = sizeof({symbol}_map),\n"
        f"    .data = {symbol}_map,\n"
        f"}};\n"
    )
    return "".join(out)


def main() -> None:
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    svg_path, size_px, symbol, out_path = sys.argv[1:]
    img = rasterize(Path(svg_path), int(size_px))
    c_source = to_c_array(img, symbol, svg_path)
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(c_source)
    print(f"Wrote {out_path} ({img.size[0]}x{img.size[1]}, {len(c_source)} bytes of source)")


if __name__ == "__main__":
    main()
