#!/usr/bin/env python3
"""Split a single-path, multi-subpath SVG (each "M...Z" a separate closed
shape sharing one fill) into individually rasterized LVGL v9 image assets,
one per subpath - used to animate the Helios logo drawing itself piece by
piece (its 12 sun-flame rays + the central disc) during boot instead of a
generic loading spinner.

Each piece is rasterized at the same px-per-SVG-unit density as a full
`canvas_px`-sized render of the whole logo, then cropped to its own tight
bounding box (Pillow's alpha getbbox()) - most of a single flame's canvas
is transparent, so the saved assets end up far smaller than one full-canvas
image per piece would.

Usage:
    python3 svg_pieces_to_lvgl.py <input.svg> <canvas_px> <symbol_prefix> <output.c> <output.h>

Requires `rsvg-convert` and Pillow, same as svg_to_lvgl.py.
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install pillow")

SVG_VIEWBOX_SIZE = 512  # matches assets/brand/helios-logo.svg's viewBox


def rasterize_piece(path_d: str, fill: str, canvas_px: int) -> "Image.Image":
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{canvas_px}" height="{canvas_px}" '
        f'viewBox="0 0 {SVG_VIEWBOX_SIZE} {SVG_VIEWBOX_SIZE}">'
        f'<path fill="{fill}" d="{path_d}"/></svg>'
    )
    with tempfile.NamedTemporaryFile(suffix=".svg", mode="w", delete=False) as f:
        f.write(svg)
        svg_path = f.name
    with tempfile.NamedTemporaryFile(suffix=".png") as png:
        subprocess.run(
            [
                "rsvg-convert", "-w", str(canvas_px), "-h", str(canvas_px),
                "--background-color=none", svg_path, "-o", png.name,
            ],
            check=True,
        )
        return Image.open(png.name).convert("RGBA").copy()


def image_to_c_array(img: "Image.Image") -> str:
    w, h = img.size
    pixels = img.load()
    row_chunks = []
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b, a = pixels[x, y]
            row.extend([b, g, r, a])  # BGRA, little-endian ARGB8888 on Xtensa
        row_chunks.append("  " + ", ".join(f"0x{v:02x}" for v in row) + ",")
    return "\n".join(row_chunks)


def main():
    if len(sys.argv) != 6:
        sys.exit(__doc__)
    src_svg = Path(sys.argv[1])
    canvas_px = int(sys.argv[2])
    prefix = sys.argv[3]
    out_c = Path(sys.argv[4])
    out_h = Path(sys.argv[5])

    svg_text = src_svg.read_text()
    path_m = re.search(r'<path[^>]*\bd="([^"]+)"', svg_text)
    fill_m = re.search(r'fill="(#[0-9a-fA-F]{6})"', svg_text)
    if not path_m:
        sys.exit(f"no <path d=...> found in {src_svg}")
    d = path_m.group(1)
    fill = fill_m.group(1) if fill_m else "#efb428"

    segments = re.findall(r"M[^M]*", d)
    print(f"{len(segments)} subpaths found in {src_svg}")

    c_parts = [
        f"/* Generated by tools/asset-gen/svg_pieces_to_lvgl.py from {src_svg.name}.\n"
        f"   Do not edit by hand - regenerate instead. */\n"
        f'#include "{out_h.name}"\n'
        f"#ifndef LV_ATTRIBUTE_MEM_ALIGN\n#define LV_ATTRIBUTE_MEM_ALIGN\n#endif\n"
    ]
    entries = []

    for i, seg in enumerate(segments):
        img = rasterize_piece(seg, fill, canvas_px)
        bbox = img.getbbox()
        if bbox is None:
            print(f"piece {i}: empty, skipping")
            continue
        cropped = img.crop(bbox)
        w, h = cropped.size
        # Offset of this piece's own center from the full canvas's center,
        # in canvas pixels - what boot_animation.c needs for
        # lv_obj_align(piece, LV_ALIGN_CENTER, dx, dy).
        left, top, right, bottom = bbox
        dx = (left + right) / 2.0 - canvas_px / 2.0
        dy = (top + bottom) / 2.0 - canvas_px / 2.0

        symbol = f"{prefix}_{i:02d}"
        c_parts.append(
            f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {symbol}_map[] = {{\n"
            f"{image_to_c_array(cropped)}\n}};\n"
            f"const lv_image_dsc_t {symbol} = {{\n"
            f"    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
            f"    .header.cf = LV_COLOR_FORMAT_ARGB8888,\n"
            f"    .header.flags = 0,\n"
            f"    .header.w = {w},\n"
            f"    .header.h = {h},\n"
            f"    .header.stride = {w} * 4,\n"
            f"    .data_size = sizeof({symbol}_map),\n"
            f"    .data = {symbol}_map,\n"
            f"}};\n"
        )
        entries.append((symbol, round(dx), round(dy)))
        print(f"piece {i}: {canvas_px}x{canvas_px} canvas -> {w}x{h} at ({dx:.0f},{dy:.0f})")

    c_parts.append(
        f"const {prefix}_piece_t {prefix}_pieces[{prefix.upper()}_PIECE_COUNT] = {{\n"
        + "\n".join(f"    {{ &{sym}, {dx}, {dy} }}," for sym, dx, dy in entries)
        + "\n};\n"
    )

    h_text = (
        f"#pragma once\n\n"
        f"/* Generated by tools/asset-gen/svg_pieces_to_lvgl.py from {src_svg.name}.\n"
        f"   Do not edit by hand - regenerate instead. */\n"
        f'#include "lvgl.h"\n\n'
        f"#define {prefix.upper()}_PIECE_COUNT {len(entries)}\n\n"
        f"typedef struct {{\n"
        f"    const lv_image_dsc_t *img;\n"
        f"    int16_t center_dx; /* offset from the logo's own center, in px, for lv_obj_align(...,LV_ALIGN_CENTER,dx,dy) */\n"
        f"    int16_t center_dy;\n"
        f"}} {prefix}_piece_t;\n\n"
        f"extern const {prefix}_piece_t {prefix}_pieces[{prefix.upper()}_PIECE_COUNT];\n"
    )

    out_c.write_text("".join(c_parts))
    out_h.write_text(h_text)
    total_bytes = sum(
        Path.stat(out_c).st_size for _ in [0]
    )
    print(f"Wrote {out_c} and {out_h}")


if __name__ == "__main__":
    main()
