#pragma once

/* Generated by tools/asset-gen/svg_pieces_to_lvgl.py from helios-logo.svg.
   Do not edit by hand - regenerate instead. */
#include "lvgl.h"

#define HELIOS_LOGO_PIECE_COUNT 13

typedef struct {
    const lv_image_dsc_t *img;
    int16_t center_dx; /* offset from the logo's own center, in px, for lv_obj_align(...,LV_ALIGN_CENTER,dx,dy) */
    int16_t center_dy;
} helios_logo_piece_t;

extern const helios_logo_piece_t helios_logo_pieces[HELIOS_LOGO_PIECE_COUNT];
